[package]
name = "matcher-benchmarks"
version = "0.1.0"
authors = ["Tibor Benke <tibor.benke@balabit.com>"]

[dependencies]
regex = "0.1"
maplit = "0.1"
log = "0.3"

[dependencies.actiondb]
# clone actiondb's source code (GitHub) into the parent dir
path = "../actiondb"
